---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-eap8
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: coolstore-eap81
spec:
  runPolicy: Serial
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: coolstore-eap81:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: coolstore-eap81
spec:
  lookupPolicy:
    local: true
