---
apiVersion: v1
kind: Namespace
metadata:
  name: coolstore-mono
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  namespace: coolstore-mono
  name: eap74-coolstore
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: eap74-coolstore:latest
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: eap74-coolstore
  namespace: coolstore-mono
