---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: coolstore-mono
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15
          env:
          - name: POSTGRESQL_DATABASE
            value: mydb
          - name: POSTGRESQL_USER
            value: myuser
          - name: POSTGRESQL_PASSWORD
            value: mypassword
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: coolstore-mono
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
