apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-bootstrap
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keycloak-bootstrap
          image: registry.redhat.io/rhbk/keycloak-rhel9:22
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              KEYCLOAK_URL="http://keycloak:8080"
              REALM="eap"
              export KCADM_CONFIG=/tmp/kcadm.config


              echo "Authenticating with Keycloak..."
              /opt/keycloak/bin/kcadm.sh config credentials \
                --server ${KEYCLOAK_URL} \
                --realm master \
                --user admin \
                --password admin \
                --config ${KCADM_CONFIG}

              echo "Creating user user1 (idempotent)..."
              /opt/keycloak/bin/kcadm.sh create users -r ${REALM} \
                -s username=user1 \
                -s enabled=true \
                -s email=user1@example.com \
                --config ${KCADM_CONFIG} || true

              echo "Ensuring user user1 exists..."

              if ! /opt/keycloak/bin/kcadm.sh get users -r ${REALM} \
                -q username=user1 --config ${KCADM_CONFIG} | grep -q '"username"'; then
                /opt/keycloak/bin/kcadm.sh create users -r ${REALM} \
                  -s username=user1 \
                  -s enabled=true \
                  -s email=user1@example.com \
                  --config ${KCADM_CONFIG}
              fi

              echo "Resolving user ID..."
              USER_ID=$(/opt/keycloak/bin/kcadm.sh get users -r ${REALM} \
                -q username=user1 \
                --fields id \
                --format csv \
                --noquotes \
                --config ${KCADM_CONFIG} | head -n 1)

              if [ -z "${USER_ID}" ]; then
                echo "ERROR: user1 ID not found"
                exit 1
              fi

              echo "Setting password for user1..."
              /opt/keycloak/bin/kcadm.sh set-password \
                -r ${REALM} \
                --userid "${USER_ID}" \
                --new-password redhat \
                --config ${KCADM_CONFIG}


              echo "Keycloak bootstrap completed at $(date)"

